### ISSUE TITLE
使用 cerebro-codelf 插件搜索变量名之后无数据返回，在 codelf 网站上搜索同样的变量名之后有数据返回。

### ISSUE THREAD

**Issue by gavinyangs** [carlos-wong/cerebro-codelf#15]
#### 例如：搜索中文变量词汇的 “地图点”，以下两图分别是 cerebro-codelf 和 codelf 网站搜索出来的结果：  
![1547000163469](https://user-images.githubusercontent.com/13849620/50871813-ceddc100-13f7-11e9-99c3-bd4bc273b67a.jpg)
![1547000247676](https://user-images.githubusercontent.com/13849620/50871819-d8672900-13f7-11e9-8cf7-8504bcfe755f.jpg)

**Comment by carlos-wong** [comment]
@gavinyangs 我检查了一下，应该是网络超时引起的。我会发布一个新版本。调整超时

**Comment by carlos-wong** [comment]
请升级到 0.1.11

**Comment by gavinyangs** [comment]
谢谢老大

carlos <notifications@github.com>于2019年1月16日 周三下午5:32写道：
