### ISSUE TITLE
【紧急】同学，请自己单独申请一个有道翻译的 API 的 KEY

### ISSUE THREAD

**Issue by unbug** [carlos-wong/cerebro-codelf#16]
我是 CODELF 的作者，CODELF 用的是有道翻译免费套餐，流量1小时1K请求就封掉了。
所以特地请求你自己申请一个有道翻译的 KEY。
https://github.com/carlos-wong/cerebro-codelf/blob/master/src/index.js#L39
你的有道翻译请求的 URL 里的 `keyfrom=Codelf&key=2023743559` 应该替换成你自己的。
e.g.
```
    http://fanyi.youdao.com/openapi.do?callback=?&keyfrom=Codelf&key=2023743559&type=data&doctype=json&version=1.1,

// replace your key
    http://fanyi.youdao.com/openapi.do?callback=?&keyfrom=cerebro-codelf&key=xxxxx-you-key-xxxxxx&type=data&doctype=json&version=1.1,
```

非常感谢！

申请有道翻译 KEY 入口 http://fanyi.youdao.com/openapi?path=data-mode

**Comment by carlos-wong** [comment]
@unbug fanyi.youdao.com 这个平台应该会被关闭吧。建议你也迁移到他们新的 api 上 https://ai.youdao.com

**Comment by unbug** [comment]
目前我还用的旧版提供的 KEY，后面再换，感谢提醒 :)

**Comment by unbug** [comment]
我的对有道翻译的请求都在前端做了缓存，同个用户相同的搜索只发一个请求，建议你也加上类似的缓存逻辑。
